Repository ku-ring/ios-app, pull requests merged in 2023-10, with the labels that each got.

#41 [2.0.0] 앱아이콘 변경 기능을 스택 기반 네비게이션으로 수정
  KuringApp/KuringApp.xcodeproj/project.pbxproj
  KuringApp/KuringApp/Setting/AppIcon/AppIconSelector.swift
  KuringApp/KuringApp/Setting/AppIcon/KuringIcon.swift
  KuringApp/KuringApp/Setting/AppIcons/kuring_app.png
  KuringApp/KuringApp/Setting/AppIcons/kuring_app_blueprint.png
  KuringApp/KuringApp/Setting/AppIcons/kuring_app_classic.png
  KuringApp/KuringApp/Setting/AppIcons/kuring_app_sketch.png
  KuringApp/KuringApp/Setting/Depedencies/AppIcons.swift
  KuringApp/KuringApp/Setting/SettingView.swift
  KuringApp/KuringApp/Setting/SettingsApp.swift
  KuringApp/KuringApp/Setting/SetttingsApp.Path.swift
Labels: enhancement, v2, 더보기

#48 [2.0.0] 자동 MERGE 테스트
  .github/workflows/BUILD_PACKAGE.yml
Labels: automerge

#50 [2.0.0] 탭바에 더보기 추가
  KuringApp/KuringApp/ContentView.swift
  KuringApp/KuringApp/Setting/SettingView.swift
  KuringApp/KuringApp/Setting/SettingsApp.swift
Labels: v2, 더보기

#39 [2.0.0] TCA기반의 검색창 구현
  KuringApp/KuringApp.xcodeproj/project.pbxproj
  KuringApp/KuringApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  KuringApp/KuringApp/Search/SearchView.swift
  KuringApp/KuringApp/Search/StaffRow.swift
  KuringModulePackage/Sources/Network/KuringLink/KuringLink.swift
  KuringModulePackage/Sources/Shared/Model/Notice.swift
  KuringModulePackage/Sources/Shared/Model/Staff.swift
Labels: v2, PBM, 검색

#53 [2.0.0] Effect.run - Unhandled error 수정
  KuringApp/KuringApp/Subscription/SubscriptionView.swift
Labels: 버그, v2, automerge

#54 [2.0.0] 구독 기능 테스트 추가
  .github/workflows/TEST_APP_TARGET_iOS17.yml
  KuringApp/KuringApp.xcodeproj/project.pbxproj
  KuringApp/KuringApp/Department/DepartmentEditor.swift
  KuringApp/KuringApp/Subscription/SubscriptionApp.swift
  KuringApp/KuringApp/Subscription/SubscriptionView.swift
  KuringApp/KuringAppTests/SubscriptionAppTests.swift
  KuringApp/KuringAppTests/SubscriptionViewTests.swift
Labels: v2, 자동화, 구독, automerge

#55 [2.0.0] test code snippet을 추가합니다
  XcodeSnippets/TestCodeSnippet.codesnippet
Labels: v2, 새로운제안, automerge
