Repository ku-ring/ios-app, pull requests merged in 2023-11, with the labels that each got.

#34 [2.0.0] TCA기반의 메인 공지화면 리스트 구현
  KuringApp/KuringApp.xcodeproj/project.pbxproj
  KuringApp/KuringApp/ContentView.swift
  KuringApp/KuringApp/Info.plist
  KuringApp/KuringApp/NoticeApp.swift
  KuringApp/KuringApp/NoticeList/DepartmentSelectorLink.swift
  KuringApp/KuringApp/NoticeList/NoticeContentView.NoDepartment.swift
  KuringApp/KuringApp/NoticeList/NoticeContentView.swift
  KuringApp/KuringApp/NoticeList/NoticeList.swift
  KuringApp/KuringApp/NoticeList/NoticeRow.swift
  KuringApp/KuringApp/NoticeList/NoticeTypeColumn.swift
  KuringApp/KuringApp/NoticeList/NoticeTypePicker.swift
  KuringApp/KuringApp/WillBeRemoved/Department.swift
  KuringApp/KuringApp/WillBeRemoved/NoticeProvider.swift
  KuringModulePackage/Package.swift
  KuringModulePackage/Sources/Feature/NoticeList/Bundle.swift
  KuringModulePackage/Sources/Feature/NoticeList/Resources/Symbols.xcassets/Contents.json
  KuringModulePackage/Sources/Feature/NoticeList/Resources/Symbols.xcassets/appIconLabel.imageset/Contents.json
  KuringModulePackage/Sources/Feature/NoticeList/Resources/Symbols.xcassets/appIconLabel.imageset/appIconLabel.png
  KuringModulePackage/Sources/Feature/NoticeList/Resources/Symbols.xcassets/appIconLabel.imageset/appIconLabel@2x.png
  KuringModulePackage/Sources/Feature/NoticeList/Resources/Symbols.xcassets/appIconLabel.imageset/appIconLabel@3x.png
  KuringModulePackage/Sources/Shared/Model/NoticeType.swift
Labels: 학과, v2, PBM, 공지리스트

#58 [2.0.0] 학과 선택 / 편집 UI 구현
  KuringApp/KuringApp/Department/DepartmentEditor.swift
  KuringApp/KuringApp/Department/DepartmentSelector.swift
  KuringApp/KuringApp/NoticeList/NoticeList.swift
Labels: 학과, automerge

#60 [2.0.0] 검색 도메인 네비게이션 작업
  KuringApp/KuringApp.xcodeproj/project.pbxproj
  KuringApp/KuringApp/NoticeApp.swift
  KuringApp/KuringApp/NoticeList/NoticeDetailView.swift
  KuringApp/KuringApp/Search/SearchView.swift
  KuringApp/KuringApp/Search/StaffDetail.swift
Labels: 검색, automerge

#65 [2.0.0] NoticeListFeature 에 없느 changeSubscription 액션을 호출하는 것으로 인한 빌드 에러 수정
  KuringApp/KuringApp/NoticeList/NoticeContentView.swift
  KuringApp/KuringApp/NoticeList/NoticeList.swift
Labels: 버그

#66 [2.0.0] 색상 사용성 개선
  KuringApp/KuringApp/Assets.xcassets/caption1.colorset/Contents.json
  KuringApp/KuringApp/Department/DepartmentEditor.swift
  KuringApp/KuringApp/Department/DepartmentSelector.swift
  KuringApp/KuringApp/NoticeList/NoticeContentView.NoDepartment.swift
  KuringApp/KuringApp/NoticeList/NoticeRow.swift
  KuringApp/KuringApp/Search/SearchView.swift
Labels: 버그, 디자인시스템, automerge
