Repository ku-ring/ios-app, pull requests merged in 2024-01, with the labels that each got.

#87 [2.0.0] NoticeFeatures 에 bookmarks 디펜던시 로직 적용
  .github/workflows/TEST_PACKAGE_TARGET_iOS17.yml
  KuringPackage/Package.swift
  KuringPackage/Sources/Features/NoticeFeatures/NoticeDetail.swift
  KuringPackage/Sources/Features/NoticeFeatures/NoticeList.swift
  KuringPackage/Sources/UIKit/NoticeUI/NoticeRow.swift
  KuringPackage/Tests/NoticeFeaturesTests/NoticeDetailTests.swift
Labels: 공지리스트, 공지보관함

#90 [2.0.0] 깃헙액션에 LabsTests 반영
  .github/workflows/TEST_PACKAGE_TARGET_iOS17.yml
Labels: 자동화

#89 [2.0.0] 이슈해결: Scoping from uncached Store is not compatible with observation
  .github/workflows/BUILD_APP_TARGET_iOS17.yml
  .github/workflows/BUILD_PACKAGE.yml
  .github/workflows/TEST_APP_TARGET_iOS17.yml
  KuringPackage/Sources/Features/SearchFeatures/Search.swift
  KuringPackage/Sources/Features/SubscriptionFeatures/SubscriptionApp.swift
  KuringPackage/Sources/UIKit/NoticeUI/DepartmentSelectorLink.swift
  KuringPackage/Sources/UIKit/NoticeUI/NoticeApp.swift
  KuringPackage/Sources/UIKit/NoticeUI/NoticeContentView.swift
  KuringPackage/Sources/UIKit/SearchUI/SearchDetailView.swift
  KuringPackage/Sources/UIKit/SearchUI/SearchView.swift
  KuringPackage/Sources/UIKit/SettingsUI/SettingsApp.swift
Labels: 버그, TCA

#91 [2.0.0] 피드백 UI
  KuringPackage/Package.swift
  KuringPackage/Sources/Features/DepartmentFeatures/DepartmentEditor.swift
  KuringPackage/Sources/Features/SearchFeatures/Search.swift
  KuringPackage/Sources/Features/SettingsFeatures/Feedback.swift
  KuringPackage/Sources/Features/SubscriptionFeatures/Subscription.swift
  KuringPackage/Sources/Networks/KuringLink.Dependency.swift
  KuringPackage/Sources/Networks/KuringLink.swift
  KuringPackage/Sources/UIKit/SettingsUI/FeedbackView.swift
  KuringPackage/Sources/UIKit/SettingsUI/Resources/AppIcons.xcassets/feedback.imageset/Contents.json
  KuringPackage/Sources/UIKit/SettingsUI/Resources/AppIcons.xcassets/feedback.imageset/feedback.png
  KuringPackage/Sources/UIKit/SettingsUI/Resources/AppIcons.xcassets/feedback.imageset/feedback@2x.png
  KuringPackage/Sources/UIKit/SettingsUI/Resources/AppIcons.xcassets/feedback.imageset/feedback@3x.png
  KuringPackage/Sources/UIKit/SettingsUI/SettingsApp.swift
Labels: 새기능/개선작업, 더보기

#93 [2.0.0] 업데이트된 디자인에 따라 피드백 UI 개선
  KuringPackage/Sources/Features/SettingsFeatures/Feedback.swift
  KuringPackage/Sources/UIKit/SettingsUI/FeedbackView.swift
Labels: v2, 더보기, automerge

#95 [2.0.0] 보관함 UI 추가
  KuringApp/KuringApp/ContentView.swift
  KuringPackage/Package.swift
  KuringPackage/Sources/Features/BookmarkFeatures/BookmarkApp.Path.swift
  KuringPackage/Sources/Features/BookmarkFeatures/BookmarkApp.swift
  KuringPackage/Sources/Features/BookmarkFeatures/BookmarkList.swift
  KuringPackage/Sources/Networks/KuringLink.Dependency.swift
  KuringPackage/Sources/Networks/KuringLink.swift
  KuringPackage/Sources/UIKit/BookmarkUI/BookmarkApp.swift
  KuringPackage/Sources/UIKit/BookmarkUI/BookmarkList.swift
  KuringPackage/Sources/UIKit/NoticeUI/NoticeDetailView.swift
  KuringPackage/Sources/UIKit/NoticeUI/NoticeRow.swift
  KuringPackage/Tests/BookmarkFeaturesTests/BookmarkListTests.swift
Labels: v2, PBM, automerge, TCA, 공지보관함

#99 [2.0.0] 작은 버그 수정 및 개선
  KuringPackage/Sources/Labs/Dependency/LeLabo.swift
  KuringPackage/Sources/Labs/ExperimentList.swift
  KuringPackage/Sources/Labs/Experiments/AppIconDetail.swift
  KuringPackage/Sources/Labs/LabApp.Path.swift
  KuringPackage/Sources/Labs/LabApp.swift
  KuringPackage/Sources/UIKit/SettingsUI/SettingList.swift
  KuringPackage/Sources/UIKit/SubscriptionUI/Resources/Symbols.xcassets/library.imageset/Contents.json
  KuringPackage/Sources/UIKit/SubscriptionUI/Resources/Symbols.xcassets/library.imageset/student.png
  KuringPackage/Sources/UIKit/SubscriptionUI/Resources/Symbols.xcassets/library.imageset/student@2x.png
  KuringPackage/Sources/UIKit/SubscriptionUI/Resources/Symbols.xcassets/library.imageset/student@3x.png
  KuringPackage/Sources/UIKit/SubscriptionUI/Resources/Symbols.xcassets/student.imageset/Contents.json
  KuringPackage/Sources/UIKit/SubscriptionUI/Resources/Symbols.xcassets/student.imageset/library.png
  KuringPackage/Sources/UIKit/SubscriptionUI/Resources/Symbols.xcassets/student.imageset/library@2x.png
  KuringPackage/Sources/UIKit/SubscriptionUI/Resources/Symbols.xcassets/student.imageset/library@3x.png
Labels: 버그, 구독, automerge, 실험실

#107 [수정] README.md 코드 관리자 수정
  README.md
Labels: 문서, 새로운제안, automerge

#112 [2.0.0] 캠퍼스맵 추가
  KuringApp/KuringApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  KuringApp/KuringApp/ContentView.swift
  package-kuring/Package.resolved
  package-kuring/Package.swift
  package-kuring/Sources/UIKit/CampusUI/CampusApp.swift
  package-kuring/Sources/UIKit/CampusUI/Resources/KuringMaps-Info.plist
Labels: automerge, 지도

#111 [2.0.0] README.md 에 SwiftFormat 추가
  README.md
Labels: 문서, automerge

#115 [2.0.0] 피드백 글자수 max 제한 미적용
  package-kuring/Sources/Features/SettingsFeatures/Feedback.swift
Labels: v2, 더보기, automerge
