Repository ku-ring/ios-app, pull requests merged in 2024-08, with the labels that each got.

#220 [2.1.1] 도서관 잔여좌석 및 실험실 위치 수정
  package-kuring/Sources/UIKit/CampusUI/CampusApp.swift
  package-kuring/Sources/UIKit/SettingsUI/SettingList.swift
Labels: 새기능/개선작업, 지도

#225 [2.2.0] 도서관 QA 사항 수정 및 개선
  package-kuring/Sources/UIKit/CampusUI/CampusApp.swift
Labels: v2, 지도

#218 [2.2.0] 쿠링봇 UI
  KuringApp/KuringApp/ContentView.swift
  package-kuring/Package.swift
  package-kuring/Sources/Features/BotFeatures/BotFeature.swift
  package-kuring/Sources/UIKit/BotUI/BotView.swift
  package-kuring/Sources/UIKit/BotUI/Bundle.swift
  package-kuring/Sources/UIKit/BotUI/ChatView.swift
  package-kuring/Sources/UIKit/BotUI/Resources/Resources.xcassets/Contents.json
  package-kuring/Sources/UIKit/BotUI/Resources/Resources.xcassets/appIcon/Contents.json
  package-kuring/Sources/UIKit/BotUI/Resources/Resources.xcassets/appIcon/kuring_app_circle.imageset/Contents.json
  package-kuring/Sources/UIKit/BotUI/Resources/Resources.xcassets/appIcon/kuring_app_circle.imageset/kuring.app.png
  package-kuring/Sources/UIKit/BotUI/Resources/Resources.xcassets/appIcon/kuring_app_circle.imageset/kuring.app2.png
  package-kuring/Sources/UIKit/BotUI/Resources/Resources.xcassets/appIcon/kuring_app_circle.imageset/kuring.app3.png
  package-kuring/Sources/UIKit/BotUI/Resources/Resources.xcassets/appIcon/kuring_app_gray.imageset/Component 1.png
  package-kuring/Sources/UIKit/BotUI/Resources/Resources.xcassets/appIcon/kuring_app_gray.imageset/Component 2.png
  package-kuring/Sources/UIKit/BotUI/Resources/Resources.xcassets/appIcon/kuring_app_gray.imageset/Component 3.png
  package-kuring/Sources/UIKit/BotUI/Resources/Resources.xcassets/appIcon/kuring_app_gray.imageset/Contents.json
  package-kuring/Sources/UIKit/BotUI/Resources/Resources.xcassets/icon/Contents.json
  package-kuring/Sources/UIKit/BotUI/Resources/Resources.xcassets/icon/icon_info_circle.imageset/Contents.json
  package-kuring/Sources/UIKit/BotUI/Resources/Resources.xcassets/icon/icon_info_circle.imageset/icon-info-circle-mono.png
  package-kuring/Sources/UIKit/BotUI/Resources/Resources.xcassets/icon/icon_info_circle.imageset/icon-info-circle-mono2.png
  package-kuring/Sources/UIKit/BotUI/Resources/Resources.xcassets/icon/icon_info_circle.imageset/icon-info-circle-mono3.png
  package-kuring/Sources/UIKit/BotUI/Resources/Resources.xcassets/icon/icon_send_white.imageset/Contents.json
  package-kuring/Sources/UIKit/BotUI/Resources/Resources.xcassets/icon/icon_send_white.imageset/Send.png
  package-kuring/Sources/UIKit/BotUI/Resources/Resources.xcassets/icon/icon_send_white.imageset/Send2.png
  package-kuring/Sources/UIKit/BotUI/Resources/Resources.xcassets/icon/icon_send_white.imageset/Send3.png
  package-kuring/Sources/UIKit/BotUI/Resources/Resources.xcassets/icon/icon_user.imageset/Contents.json
  package-kuring/Sources/UIKit/BotUI/Resources/Resources.xcassets/icon/icon_user.imageset/Frame 336-2.png
  package-kuring/Sources/UIKit/BotUI/Resources/Resources.xcassets/icon/icon_user.imageset/Frame 336-3.png
  package-kuring/Sources/UIKit/BotUI/Resources/Resources.xcassets/icon/icon_user.imageset/Frame 336.png
  package-kuring/Sources/UIKit/BotUI/SendPopup.swift
  package-kuring/Sources/UIKit/PopupUI/PopupView.swift
Labels: 새기능/개선작업, 쿠링봇

#221 [2.2.0] 쿠링봇 서버 연결
  package-kuring/Package.swift
  package-kuring/Sources/Features/BotFeatures/BotFeature.swift
  package-kuring/Sources/Networks/Depdencies/KuringLink.Dependency.swift
  package-kuring/Sources/Networks/Depdencies/SSEClient.swift
  package-kuring/Sources/Networks/KuringLink/API.Path.swift
  package-kuring/Sources/UIKit/BotUI/BotView.swift
  package-kuring/Sources/UIKit/BotUI/ChatView.swift
  package-kuring/Sources/UIKit/BotUI/Resources/Resources.xcassets/animation_loading.dataset/Contents.json
  package-kuring/Sources/UIKit/BotUI/Resources/Resources.xcassets/animation_loading.dataset/animation_loading.json
  package-kuring/Sources/UIKit/BotUI/SendPopup.swift
Labels: automerge, 쿠링봇

#226 [2.2.0] 쿠링봇 1차 QA 수정
  package-kuring/Sources/UIKit/BotUI/BotView.swift
  package-kuring/Sources/UIKit/BotUI/ChatView.swift
Labels: automerge, 쿠링봇

#229 [2.2.0] 쿠링봇 ChatView 패딩, 행간 값 수정
  package-kuring/Sources/UIKit/BotUI/ChatView.swift
Labels: automerge, 쿠링봇
