Repository ku-ring/ios-app, pull requests merged in 2024-04, with the labels that each got.

#198 [2.0.0] 공지 디테일 네비게이션 타이틀에서 카테고리 정보 보여주도록 수정
  package-kuring/Sources/Models/Notice.swift
  package-kuring/Sources/UIKit/NoticeUI/NoticeApp.swift
  package-kuring/Sources/UIKit/NoticeUI/NoticeDetailView.swift
Labels: 공지리스트, automerge

#197 [2.0.0] 온보딩 상태에서 구독로직
  KuringApp/KuringApp/Info.plist
  package-kuring/Sources/Caches/Dependency/Departments.swift
  package-kuring/Sources/Caches/Dependency/Subscriptions.swift
  package-kuring/Sources/UIKit/OnboardingUI/MyDepartmentSelector/MyDepartmentSelector.swift
Labels: 학과, PBM, 구독, automerge, 온보딩

#202 [2.0.0] apple privacyInfo 정책 대응
  KuringApp/KuringApp.xcodeproj/project.pbxproj
  KuringApp/PrivacyInfo.xcprivacy
Labels: v2, automerge

#203 [2.0.0] 공지 border 라인 마진 및 대표학과 칩 UI
  KuringApp/KuringApp.xcodeproj/project.pbxproj
  KuringApp/KuringApp/PrivacyInfo.xcprivacy
  package-kuring/Sources/UIKit/DepartmentUI/DepartmentRow.swift
  package-kuring/Sources/UIKit/NoticeUI/NoticeList.swift
Labels: v2, automerge

#204 [2.0.0] 회원 등록 api 추가 요청 대응
  KuringApp/KuringApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  package-kuring/Sources/Models/AuthRequest.swift
  package-kuring/Sources/Networks/Depdencies/KuringLink.Dependency.swift
  package-kuring/Sources/Networks/KuringLink/API.Path.swift
  package-kuring/Sources/Networks/KuringLink/KuringLink.swift
  package-kuring/Sources/PushNotifications/Notifications/Notifications.MessagingDelegate.swift
Labels: automerge
