Repository ku-ring/ios-app, pull requests merged in 2024-03, with the labels that each got.

#149 [2.0.0] 온보딩 작업
  KuringApp/KuringApp.xcodeproj/project.pbxproj
  KuringApp/KuringApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  KuringApp/KuringApp/Assets.xcassets/AccentColor.colorset/Contents.json
  KuringApp/KuringApp/KuringApp.swift
  package-kuring/Package.resolved
  package-kuring/Package.swift
  package-kuring/Sources/UIKit/DepartmentUI/DepartmentRow.swift
  package-kuring/Sources/UIKit/OnboardingUI/Bundle.swift
  package-kuring/Sources/UIKit/OnboardingUI/Common/KuringButtonStyle.swift
  package-kuring/Sources/UIKit/OnboardingUI/Common/StringSet.swift
  package-kuring/Sources/UIKit/OnboardingUI/MyDepartmentSelector/CompletionView.swift
  package-kuring/Sources/UIKit/OnboardingUI/MyDepartmentSelector/ConfirmationView.swift
  package-kuring/Sources/UIKit/OnboardingUI/MyDepartmentSelector/DepartmentSelector.swift
  package-kuring/Sources/UIKit/OnboardingUI/MyDepartmentSelector/MyDepartmentSelector.Step.swift
  package-kuring/Sources/UIKit/OnboardingUI/MyDepartmentSelector/MyDepartmentSelector.swift
  package-kuring/Sources/UIKit/OnboardingUI/OnboardingView/OnboardingView.Guidance.swift
  package-kuring/Sources/UIKit/OnboardingUI/OnboardingView/OnboardingView.GuidanceView.swift
  package-kuring/Sources/UIKit/OnboardingUI/OnboardingView/OnboardingView.swift
  package-kuring/Sources/UIKit/OnboardingUI/Resources/Symbols.xcassets/Contents.json
  package-kuring/Sources/UIKit/OnboardingUI/Resources/Symbols.xcassets/bell.notice.alert.new.3d.imageset/Contents.json
  package-kuring/Sources/UIKit/OnboardingUI/Resources/Symbols.xcassets/bell.notice.alert.new.3d.imageset/bell.notice.alert.new.3d.png
  package-kuring/Sources/UIKit/OnboardingUI/Resources/Symbols.xcassets/bell.notice.alert.new.3d.imageset/bell.notice.alert.new.3d@2x.png
  package-kuring/Sources/UIKit/OnboardingUI/Resources/Symbols.xcassets/bell.notice.alert.new.3d.imageset/bell.notice.alert.new.3d@3x.png
  package-kuring/Sources/UIKit/OnboardingUI/Resources/Symbols.xcassets/magnifyingglass.3d.imageset/Contents.json
  package-kuring/Sources/UIKit/OnboardingUI/Resources/Symbols.xcassets/magnifyingglass.3d.imageset/magnifyingglass.3d.png
  package-kuring/Sources/UIKit/OnboardingUI/Resources/Symbols.xcassets/magnifyingglass.3d.imageset/magnifyingglass.3d@2x.png
  package-kuring/Sources/UIKit/OnboardingUI/Resources/Symbols.xcassets/magnifyingglass.3d.imageset/magnifyingglass.3d@3x.png
  package-kuring/Sources/UIKit/OnboardingUI/Resources/Symbols.xcassets/smartphone.with.hand.3d.imageset/Contents.json
  package-kuring/Sources/UIKit/OnboardingUI/Resources/Symbols.xcassets/smartphone.with.hand.3d.imageset/smartphone.with.hand.3d.png
  package-kuring/Sources/UIKit/OnboardingUI/Resources/Symbols.xcassets/smartphone.with.hand.3d.imageset/smartphone.with.hand.3d@2x.png
  package-kuring/Sources/UIKit/OnboardingUI/Resources/Symbols.xcassets/smartphone.with.hand.3d.imageset/smartphone.with.hand.3d@3x.png
  package-kuring/Sources/UIKit/OnboardingUI/Resources/Symbols.xcassets/success.dataset/Contents.json
  package-kuring/Sources/UIKit/OnboardingUI/Resources/Symbols.xcassets/success.dataset/success.json
Labels: automerge, 온보딩

#156 [2.0.0] 다크모드 대응
  package-kuring/Sources/UIKit/BookmarkUI/BookmarkList.swift
  package-kuring/Sources/UIKit/DepartmentUI/DepartmentEditor.swift
  package-kuring/Sources/UIKit/DepartmentUI/DepartmentRow.swift
  package-kuring/Sources/UIKit/NoticeUI/NoticeApp.swift
  package-kuring/Sources/UIKit/NoticeUI/NoticeContentView.NoDepartment.swift
  package-kuring/Sources/UIKit/NoticeUI/NoticeRow.swift
  package-kuring/Sources/UIKit/NoticeUI/NoticeTypeColumn.swift
  package-kuring/Sources/UIKit/OnboardingUI/MyDepartmentSelector/DepartmentSelector.swift
  package-kuring/Sources/UIKit/SearchUI/SearchView.swift
Labels: v2, 공지리스트, 검색, 디자인시스템, automerge, 공지보관함, 온보딩

#148 [2.0.0] 세팅 UI 구현
  KuringApp/KuringApp.xcodeproj/project.pbxproj
  package-kuring/Sources/Labs/ExperimentList.swift
  package-kuring/Sources/UIKit/ColorSet/Color.UIKit.swift
  package-kuring/Sources/UIKit/SettingsUI/AppIconSelector.swift
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/Contents.json
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/appIcon/Contents.json
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/appIcon/kuring_app.imageset/Contents.json
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/appIcon/kuring_app.imageset/kuring_app.png
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/appIcon/kuring_app_blueprint.imageset/Contents.json
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/appIcon/kuring_app_blueprint.imageset/kuring_app_blueprint.png
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/appIcon/kuring_app_classic.imageset/Contents.json
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/appIcon/kuring_app_classic.imageset/kuring_app_classic.png
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/appIcon/kuring_app_sketch.imageset/Contents.json
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/appIcon/kuring_app_sketch.imageset/kuring_app_sketch.png
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/feedback.imageset/Contents.json
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/feedback.imageset/feedback.png
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/feedback.imageset/feedback@2x.png
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/feedback.imageset/feedback@3x.png
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/Contents.json
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/chevron.imageset/Contents.json
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/chevron.imageset/chevron.png
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/chevron.imageset/chevron@2x.png
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/chevron.imageset/chevron@3x.png
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/icon_bell.imageset/Contents.json
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/icon_bell.imageset/icon_bell.png
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/icon_bell.imageset/notice@2x.png
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/icon_bell.imageset/notice@3x.png
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/icon_checkmark_circle.imageset/Contents.json
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/icon_checkmark_circle.imageset/icon_checkmark_circle.png
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/icon_checkmark_circle.imageset/icon_checkmark_circle@2x.png
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/icon_checkmark_circle.imageset/icon_checkmark_circle@3x.png
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/icon_feedback.imageset/Contents.json
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/icon_feedback.imageset/icon_feedback.png
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/icon_feedback.imageset/icon_feedback@2x.png
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/icon_feedback.imageset/icon_feedback@3x.png
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/icon_guard.imageset/Contents.json
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/icon_guard.imageset/icon_guard.png
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/icon_guard.imageset/icon_guard@2x.png
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/icon_guard.imageset/icon_guard@3x.png
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/icon_instagram.imageset/Contents.json
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/icon_instagram.imageset/icon_instagram.png
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/icon_instagram.imageset/icon_instagram@2x.png
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/icon_instagram.imageset/icon_instagram@3x.png
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/icon_opensource.imageset/Contents.json
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/icon_opensource.imageset/icon_opensource.png
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/icon_opensource.imageset/icon_opensource@2x.png
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/icon_opensource.imageset/icon_opensource@3x.png
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/icon_rocket.imageset/Contents.json
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/icon_rocket.imageset/icon_app_version.png
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/icon_rocket.imageset/icon_app_vserion@2x.png
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/icon_rocket.imageset/icon_app_vserion@3x.png
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/icon_star.imageset/Contents.json
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/icon_star.imageset/icon_new.png
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/icon_star.imageset/icon_new@2x.png
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/icon_star.imageset/icon_new@3x.png
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/icon_team.imageset/Contents.json
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/icon_team.imageset/icon_team.png
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/icon_team.imageset/icon_team@2x.png
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/icon_team.imageset/icon_team@3x.png
  package-kuring/Sources/UIKit/SettingsUI/SettingList.swift
Labels: v2, 더보기

#155 [2.0.0] 공지사항 UI에 발생하던 이슈 수정
  package-kuring/Sources/UIKit/BookmarkUI/BookmarkList.swift
  package-kuring/Sources/UIKit/DepartmentUI/DepartmentEditor.swift
  package-kuring/Sources/UIKit/DepartmentUI/DepartmentRow.swift
  package-kuring/Sources/UIKit/NoticeUI/NoticeApp.swift
  package-kuring/Sources/UIKit/NoticeUI/NoticeContentView.NoDepartment.swift
  package-kuring/Sources/UIKit/NoticeUI/NoticeList.swift
  package-kuring/Sources/UIKit/NoticeUI/NoticeRow.swift
  package-kuring/Sources/UIKit/NoticeUI/NoticeTypeColumn.swift
  package-kuring/Sources/UIKit/OnboardingUI/MyDepartmentSelector/DepartmentSelector.swift
  package-kuring/Sources/UIKit/SearchUI/SearchView.swift
Labels: v2, 공지리스트, 디자인시스템

#158 [2.0.0] 다크모드 전부 적용 및 학과 공지 UI 버그 및 다크모드 색상 적용을 위한 UI 수정
  KuringApp/KuringApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  package-kuring/Sources/Labs/ExperimentList.swift
  package-kuring/Sources/Labs/Experiments/AppIconDetail.swift
  package-kuring/Sources/Labs/Experiments/BetaADetail.swift
  package-kuring/Sources/UIKit/BookmarkUI/BookmarkList.swift
  package-kuring/Sources/UIKit/DepartmentUI/DepartmentEditor.swift
  package-kuring/Sources/UIKit/DepartmentUI/DepartmentRow.swift
  package-kuring/Sources/UIKit/DepartmentUI/DepartmentSelector.swift
  package-kuring/Sources/UIKit/NoticeUI/DepartmentSelectorLink.swift
  package-kuring/Sources/UIKit/NoticeUI/NoticeList.swift
  package-kuring/Sources/UIKit/NoticeUI/NoticeRow.swift
  package-kuring/Sources/UIKit/OnboardingUI/Common/KuringButtonStyle.swift
  package-kuring/Sources/UIKit/OnboardingUI/MyDepartmentSelector/CompletionView.swift
  package-kuring/Sources/UIKit/OnboardingUI/MyDepartmentSelector/ConfirmationView.swift
  package-kuring/Sources/UIKit/OnboardingUI/MyDepartmentSelector/DepartmentSelector.swift
  package-kuring/Sources/UIKit/OnboardingUI/MyDepartmentSelector/MyDepartmentSelector.swift
  package-kuring/Sources/UIKit/OnboardingUI/OnboardingView/OnboardingView.swift
  package-kuring/Sources/UIKit/SearchUI/SearchDetailView.swift
  package-kuring/Sources/UIKit/SearchUI/SearchView.swift
  package-kuring/Sources/UIKit/SettingsUI/AppIconSelector.swift
  package-kuring/Sources/UIKit/SettingsUI/FeedbackView.swift
  package-kuring/Sources/UIKit/SettingsUI/OpenSourceList.swift
  package-kuring/Sources/UIKit/SettingsUI/SettingList.swift
  package-kuring/Sources/UIKit/SubscriptionUI/SubscriptionSegment.swift
  package-kuring/Sources/UIKit/SubscriptionUI/SubscriptionView.swift
Labels: 학과, v2, 공지리스트, 디자인시스템

#161 [2.0.0] Models hashValue 수정
  package-kuring/Sources/Models/Notice.swift
  package-kuring/Sources/Models/NoticeProvider.swift
Labels: v2, PBM

#165 [2.0.0] Cache > Dependency > 검색
  package-kuring/Sources/Caches/RecentSearch.swift
  package-kuring/Sources/Caches/UserDefault.swift
Labels: v2, 검색, automerge, TCA

#172 [2.0.0] Cache base branch
  package-kuring/Sources/Caches/Dependency/AppIcons.swift
  package-kuring/Sources/Caches/Dependency/Bookmarks.swift
  package-kuring/Sources/Caches/Dependency/Spotlight.swift
  package-kuring/Sources/Caches/Extensions/Array+.swift
  package-kuring/Sources/Caches/Extensions/Set+.swift
  package-kuring/Sources/Caches/Utils/StringSet.swift
  package-kuring/Sources/Caches/Utils/UserDefault.swift
Labels: automerge

#170 [2.0.0] Cache > Dependency > Auth
  package-kuring/Sources/Caches/Dependency/Auth.swift
Labels: 새기능/개선작업, v2, TCA

#169 [2.0.0] Cache > Dependency > Commons
  package-kuring/Sources/Caches/Dependency/Commons.swift
  package-kuring/Sources/Caches/Utils/StringSet.swift
Labels: v2, automerge, TCA, 온보딩

#174 [2.0.0] UI 에러와 모듈네임 컴파일 에러 수정
  package-kuring/Package.swift
  package-kuring/Sources/Caches/Dependency/Auth.swift
  package-kuring/Sources/Caches/Dummy.swift
  package-kuring/Sources/Labs/ExperimentList.swift
  package-kuring/Sources/Labs/Experiments/AppIconDetail.swift
  package-kuring/Sources/Labs/Experiments/BetaADetail.swift
  package-kuring/Sources/UIKit/BookmarkUI/BookmarkList.swift
  package-kuring/Sources/UIKit/ColorSet/Color.UIKit.swift
  package-kuring/Sources/UIKit/DepartmentUI/DepartmentEditor.swift
  package-kuring/Sources/UIKit/DepartmentUI/DepartmentRow.swift
  package-kuring/Sources/UIKit/DepartmentUI/DepartmentSelector.swift
  package-kuring/Sources/UIKit/NoticeUI/DepartmentSelectorLink.swift
  package-kuring/Sources/UIKit/NoticeUI/NoticeApp.swift
  package-kuring/Sources/UIKit/NoticeUI/NoticeContentView.NoDepartment.swift
  package-kuring/Sources/UIKit/NoticeUI/NoticeContentView.swift
  package-kuring/Sources/UIKit/NoticeUI/NoticeList.swift
  package-kuring/Sources/UIKit/NoticeUI/NoticeRow.swift
  package-kuring/Sources/UIKit/NoticeUI/NoticeTypeColumn.swift
  package-kuring/Sources/UIKit/OnboardingUI/Common/KuringButtonStyle.swift
  package-kuring/Sources/UIKit/OnboardingUI/MyDepartmentSelector/CompletionView.swift
  package-kuring/Sources/UIKit/OnboardingUI/MyDepartmentSelector/ConfirmationView.swift
  package-kuring/Sources/UIKit/OnboardingUI/MyDepartmentSelector/DepartmentSelector.swift
  package-kuring/Sources/UIKit/OnboardingUI/MyDepartmentSelector/MyDepartmentSelector.swift
  package-kuring/Sources/UIKit/OnboardingUI/OnboardingView/OnboardingView.swift
  package-kuring/Sources/UIKit/SearchUI/SearchView.swift
  package-kuring/Sources/UIKit/SearchUI/StaffRow.swift
  package-kuring/Sources/UIKit/SettingsUI/AppIconSelector.swift
  package-kuring/Sources/UIKit/SettingsUI/FeedbackView.swift
  package-kuring/Sources/UIKit/SettingsUI/OpenSourceList.swift
  package-kuring/Sources/UIKit/SettingsUI/SettingList.swift
  package-kuring/Sources/UIKit/SubscriptionUI/SubscriptionSegment.swift
  package-kuring/Sources/UIKit/SubscriptionUI/SubscriptionView.swift
Labels: 버그, 디자인시스템, automerge

#173 [2.0.0] 최근 검색어 기능 구현
  package-kuring/Sources/Caches/Dependency/RecentSearch.swift
  package-kuring/Sources/Features/SearchFeatures/Search.swift
  package-kuring/Sources/UIKit/SearchUI/SearchView.swift
Labels: 새기능/개선작업, v2, 검색, automerge, TCA

#178 [2.0.0] 공지 웹뷰 영역 다크모드 대응
  package-kuring/Sources/UIKit/NoticeUI/NoticeDetailView.swift
Labels: v2, 디자인시스템, automerge

#176 [2.0.0] 대학 및 학과 구독 로직
  package-kuring/Sources/Caches/Dependency/Subscriptions.swift
  package-kuring/Sources/Features/SubscriptionFeatures/Subscription.swift
  package-kuring/Sources/Models/NoticeProvider.swift
Labels: 학과, v2, 구독, automerge

#180 [2.0.0] `Color.Kuring.warning` 색상 오류 수정
  KuringApp/KuringApp/Assets.xcassets/AccentColor.colorset/Contents.json
  package-kuring/Sources/UIKit/ColorSet/Color.UIKit.swift
Labels: 버그, 디자인시스템, automerge

#182 [수정] README.md 배지 수정
  README.md
Labels: 문서

#181 [2.0.0] `Package.resolved` 해시 변경
  KuringApp/KuringApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  package-kuring/Package.resolved
Labels: 버그, 자동화

#183 [2.0.0] 사용된 오픈소스 페이지
  package-kuring/Sources/Features/SettingsFeatures/OpenSourceListFeature.swift
  package-kuring/Sources/Features/SettingsFeatures/SettingList.swift
  package-kuring/Sources/Features/SettingsFeatures/SettingsApp.Destination.swift
  package-kuring/Sources/Features/SettingsFeatures/SettingsApp.Path.swift
  package-kuring/Sources/Features/SettingsFeatures/SettingsApp.swift
  package-kuring/Sources/UIKit/SettingsUI/OpenSourceList.swift
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/icon_external_link.imageset/Contents.json
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/icon_external_link.imageset/icon_external_link.png
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/icon_external_link.imageset/icon_external_link@2x.png
  package-kuring/Sources/UIKit/SettingsUI/Resources/Resources.xcassets/setting/icon_external_link.imageset/icon_external_link@3x.png
  package-kuring/Sources/UIKit/SettingsUI/SettingList.swift
  package-kuring/Sources/UIKit/SettingsUI/SettingsApp.swift
Labels: 더보기, automerge

#185 [2.0.0] 온보딩 연결 로직
  KuringApp/KuringApp/KuringApp.swift
  package-kuring/Sources/Caches/Dependency/Commons.swift
  package-kuring/Sources/UIKit/OnboardingUI/OnboardingView/OnboardingView.swift
Labels: v2, automerge, TCA, 온보딩

#193 [2.0.0] 이상한 네이밍 수정
  KuringApp/KuringApp/KuringApp.swift
  package-kuring/Sources/Caches/Dependency/Commons.swift
Labels: v2, 온보딩

#192 [2.0.0] 캠퍼스맵 `Appearance` 에 `ColorSet` 적용
  KuringApp/KuringApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  package-kuring/Package.swift
  package-kuring/Sources/UIKit/CampusUI/CampusApp.swift
Labels: automerge, 지도

#190 [2.0.0] 학과 검색 로직 추가 및 공유하기 버그 수정
  package-kuring/Sources/Features/DepartmentFeatures/DepartmentEditor.swift
  package-kuring/Sources/Features/DepartmentFeatures/DepartmentSearchEngine.swift
  package-kuring/Sources/Features/NoticeFeatures/NoticeDetail.swift
  package-kuring/Sources/UIKit/DepartmentUI/DepartmentEditor.swift
  package-kuring/Sources/UIKit/NoticeUI/NoticeApp.swift
  package-kuring/Sources/UIKit/NoticeUI/NoticeDetailView.swift
  package-kuring/Sources/UIKit/SearchUI/SearchView.swift
  package-kuring/Sources/UIKit/SubscriptionUI/SubscriptionApp.swift
Labels: 학과, v2, 공지리스트, automerge
