Repository ku-ring/ios-app, pull requests merged in 2024-02, with the labels that each got.

#120 [2.0.0] TCA 버전 1.7 로 업데이트
  README.md
  package-kuring/Package.resolved
  package-kuring/Package.swift
Labels: automerge, TCA

#122 [2.0.0] 공지 리스트와 디테일 간의 북마크 싱크 안 맞는 이슈 해결
  package-kuring/Sources/Features/DepartmentFeatures/DepartmentSelector.swift
  package-kuring/Sources/Features/NoticeFeatures/NoticeApp.Path.swift
  package-kuring/Sources/Features/NoticeFeatures/NoticeApp.swift
  package-kuring/Sources/Features/NoticeFeatures/NoticeDetail.swift
  package-kuring/Sources/Features/NoticeFeatures/NoticeList.swift
  package-kuring/Sources/Features/SearchFeatures/Search.swift
  package-kuring/Sources/Features/SearchFeatures/StaffDetail.swift
  package-kuring/Sources/Models/NoticeProvider.swift
  package-kuring/Sources/UIKit/NoticeUI/NoticeList.swift
  package-kuring/Sources/UIKit/NoticeUI/NoticeRow.swift
  package-kuring/Tests/NoticeFeaturesTests/NoticeAppTests.swift
  package-kuring/Tests/NoticeFeaturesTests/NoticeDetailTests.swift
Labels: 버그, 공지리스트, automerge, 공지보관함

#98 [2.0.0] 커밋 방지 처리 스크립트 추가
  .github/scripts/Commit_Guardian.sh
  FIRST_ACTION.sh
  README.md
  package-kuring/Sources/Networks/Resources/KuringLink-Info.plist
  package-kuring/Sources/UIKit/CampusUI/CampusApp.swift
Labels: 자동화

#125 [2.0.0] 버전 업데이트 알림 기능 추가
  package-kuring/.swiftpm/xcode/xcshareddata/xcschemes/NetworksTests.xcscheme
  package-kuring/.swiftpm/xcode/xcshareddata/xcschemes/package-kuring-Package.xcscheme
  package-kuring/Package.swift
  package-kuring/Sources/Features/NoticeFeatures/NoticeList.swift
  package-kuring/Sources/Features/SearchFeatures/Search.swift
  package-kuring/Sources/Features/SettingsFeatures/Feedback.swift
  package-kuring/Sources/Features/SubscriptionFeatures/Subscription.swift
  package-kuring/Sources/Networks/AppSupport/AppSupport.swift
  package-kuring/Sources/Networks/AppSupport/AppSupportClient.swift
  package-kuring/Sources/Networks/Depdencies/AppSupport.Dependency.swift
  package-kuring/Sources/Networks/Depdencies/KuringLink.Dependency.swift
  package-kuring/Sources/Networks/KuringLink/API.Path.swift
  package-kuring/Sources/Networks/KuringLink/API.Response.swift
  package-kuring/Sources/Networks/KuringLink/KuringLink.swift
  package-kuring/Sources/UIKit/CommonUI/View.VersionUpdateAlert.swift
  package-kuring/Tests/NetworksTests/AppSupportClientTests.swift
Labels: 새기능/개선작업, v2, automerge

#133 [2.0.0] 오픈소스 라이센스 보여주도록 수정
  package-kuring/Sources/Features/SettingsFeatures/OpenSourceListFeature.swift
  package-kuring/Sources/UIKit/SettingsUI/OpenSourceList.swift
  package-kuring/Sources/UIKit/SettingsUI/SettingList.swift
  package-kuring/Sources/UIKit/SettingsUI/SettingsApp.swift
Labels: v2, 더보기, automerge

#135 [2.0.0] SubscriptionAppTests 시나리오 테스트 수정
  package-kuring/Tests/SubscriptionFeaturesTests/SubscriptionAppTests.swift
Labels: v2, automerge

#134 [2.0.0] 공지 공유하기
  KuringApp/KuringApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  package-kuring/Package.resolved
  package-kuring/Package.swift
  package-kuring/Sources/Features/NoticeFeatures/Extensions/ActivityItem.Equatable.swift
  package-kuring/Sources/Features/NoticeFeatures/NoticeDetail.swift
  package-kuring/Sources/UIKit/NoticeUI/NoticeDetailView.swift
  package-kuring/Tests/NoticeFeaturesTests/NoticeDetailTests.swift
  package-kuring/Tests/SubscriptionFeaturesTests/SubscriptionAppTests.swift
Labels: v2, 공지리스트, automerge

#136 [2.0.0] 북마크 한 공지가 없는 상황에서의 UI 추가
  package-kuring/Sources/UIKit/BookmarkUI/BookmarkList.swift
Labels: automerge, 공지보관함

#140 [2.0.0] 푸시 알림 처리 & 1주일 공지 미확인 알림
  .gitignore
  KuringApp/KuringApp.xcodeproj/project.pbxproj
  KuringApp/KuringApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  KuringApp/KuringApp/Info.plist
  KuringApp/KuringApp/KuringApp.entitlements
  KuringApp/KuringApp/KuringApp.swift
  README.md
  package-kuring/.swiftpm/xcode/xcshareddata/xcschemes/package-kuring-Package.xcscheme
  package-kuring/Package.resolved
  package-kuring/Package.swift
  package-kuring/Sources/Models/Notice.swift
  package-kuring/Sources/PushNotifications/Errors/MessageError.swift
  package-kuring/Sources/PushNotifications/Extensions/DateComponents.swift
  package-kuring/Sources/PushNotifications/Message/Message.swift
  package-kuring/Sources/PushNotifications/Notifications/Notifications.MessagingDelegate.swift
  package-kuring/Sources/PushNotifications/Notifications/Notifications.UIApplicationDelegate.swift
  package-kuring/Sources/PushNotifications/Notifications/Notifications.UNUserNotificationCenterDelegate.swift
  package-kuring/Sources/PushNotifications/Notifications/Notifications.swift
  package-kuring/Sources/PushNotifications/Publishers/Publishers.swift
Labels: PBM, 푸시알림

#139 [2.0.0] 스포트라이트 검색 기능
  package-kuring/Sources/Caches/Bookmarks.swift
  package-kuring/Sources/Caches/Spotlight.swift
Labels: 새기능/개선작업, automerge, TCA

#144 [2.0.0] v2 웹뷰 및 NoticeRow 화면전환 연결
  package-kuring/Package.swift
  package-kuring/Sources/Features/BookmarkFeatures/BookmarkApp.swift
  package-kuring/Sources/UIKit/BookmarkUI/BookmarkList.swift
  package-kuring/Sources/UIKit/CommonUI/WebView.swift
  package-kuring/Sources/UIKit/NoticeUI/NoticeApp.swift
  package-kuring/Sources/UIKit/NoticeUI/NoticeDetailView.swift
  package-kuring/Sources/UIKit/NoticeUI/NoticeList.swift
  package-kuring/Sources/UIKit/NoticeUI/NoticeRow.swift
Labels: PBM, 공지리스트, 공지보관함

#146 [2.0.0] 버그 수정: [RTIInputSystemClient remoteTextInputSessionWithID:performInputOperation:] perform input operation requires a valid sessionID
  package-kuring/Sources/UIKit/DepartmentUI/DepartmentEditor.swift
  package-kuring/Sources/UIKit/SearchUI/SearchView.swift
Labels: 학과, 검색, 외부 버그, automerge

#143 [2.0.0] 공지 카테고리 관련 API 요청 인터페이스 추가 및 구현
  KuringApp/KuringApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  KuringApp/KuringApp/KuringApp.swift
  package-kuring/Package.resolved
  package-kuring/Package.swift
  package-kuring/Sources/Features/DepartmentFeatures/DepartmentEditor.swift
  package-kuring/Sources/Features/NoticeFeatures/NoticeApp.swift
  package-kuring/Sources/Features/NoticeFeatures/NoticeList.swift
  package-kuring/Sources/Features/SubscriptionFeatures/Subscription.swift
  package-kuring/Sources/Models/Notice.swift
  package-kuring/Sources/Models/NoticeProvider.swift
  package-kuring/Sources/Models/Staff.swift
  package-kuring/Sources/Models/Subscription.swift
  package-kuring/Sources/Networks/Depdencies/KuringLink.Dependency.swift
  package-kuring/Sources/Networks/KuringLink/KuringLink.swift
  package-kuring/Sources/PushNotifications/Message/Message.swift
  package-kuring/Sources/UIKit/CommonUI/View.onFetchAllData.swift
  package-kuring/Sources/UIKit/DepartmentUI/DepartmentEditor.swift
  package-kuring/Sources/UIKit/NoticeUI/NoticeContentView.NoDepartment.swift
  package-kuring/Sources/UIKit/NoticeUI/NoticeTypeColumn.swift
  package-kuring/Sources/UIKit/NoticeUI/NoticeTypePicker.swift
  package-kuring/Sources/UIKit/SubscriptionUI/SubscriptionView.swift
  package-kuring/Tests/SubscriptionFeaturesTests/SubscriptionAppTests.swift
Labels: 학과, 구독
